Testing main
Tris20/FairFareFinder pull request #206
Opened 2024-12-14 21:38 UTC by mrjkey

- setup tests for combinedCardsHandler 
- fixed test for filter handler
- updated how the server is initialized and starts, so it is easy to test using a debugger
- updated mock database location so that test database will be directly referenced, and in a different location to the production db

2024-12-14 23:41 UTC, Tris20 commented on .github/workflows/main-branch.yml
> +      # # Step 6: Start the main application with the --web flag
Good call, we don't need to run main --web now stable exists

2024-12-14 23:43 UTC, Tris20 commented on main.go
> +// TODO: move types to a separate file
Agreed, but would rather avoid todos in the code
```suggestion
```

2024-12-14 23:50 UTC, Tris20 commented on main.go
> +	// Note: uncomment this when debugging. During tests it makes the output too long
I thought about deleting this section, but it's actually very very useful for displaying the dynamic SQL queries. Ideally it lives somewhere else in the future

2024-12-15 00:02 UTC, Tris20 requested changes

2024-12-15 00:02 UTC, Tris20 commented on main_test.go
lgtm

2024-12-15 10:08 UTC, mrjkey commented on main.go
> +	// Note: uncomment this when debugging. During tests it makes the output too long
Do you know if there is a way to turn this off during particular modes? Because when running a test you can't see what the test results are, the page is just full of prints

2024-12-15 10:13 UTC, mrjkey commented on main.go
> +	}()
While updating the tests, `defer rows.Close()` would case a runtime panic if the query didn't return anything, so the change is to wrap the close in a nil check. This still runs with defer, but doesn't attempt to run .Close if the object is nil

2024-12-15 10:13 UTC, mrjkey commented on main.go
> -		log.Printf("Row Data - Destination: %s, Date: %s, Temp: %.2f, Icon: %s, Duration.Mins %.2f",
Similar to the other comment, do you know if there is a way to not run this during tests? While running the test it becomes really hard to see the result from the test

2024-12-15 10:13 UTC, mrjkey commented on main.go
> -		log.Printf("Scanned image URL: '%s', Valid: %t", imageUrl.String, imageUrl.Valid)
https://github.com/Tris20/FairFareFinder/pull/206/files/70e1c12c7e2d94457aae37cb97c3a8f44367117a#r1885429415

2024-12-15 10:13 UTC, mrjkey commented on main.go
> +// TODO: move these somehwere else.
removed

2024-12-15 10:13 UTC, mrjkey commented on main.go
> +// TODO: move types to another file
removed

2024-12-15 10:14 UTC, mrjkey commented on main.go
> +// TODO: find where these can stay, but not here
removed

2024-12-15 11:12 UTC, mrjkey commented on main.go
> +	// Note: uncomment this when debugging. During tests it makes the output too long
Added flag to mute the prints

2024-12-15 11:12 UTC, mrjkey commented on main.go
> -		log.Printf("Row Data - Destination: %s, Date: %s, Temp: %.2f, Icon: %s, Duration.Mins %.2f",
logs are active again, during tests we can route them somewhere else

2024-12-15 12:19 UTC, mrjkey commented
rebased from main

2024-12-15 12:56 UTC, Tris20 commented on main.go
> +	}()
Sounds like a reasonable fix

2024-12-15 12:58 UTC, Tris20 commented on main.go
> +			flight.DurationHourDotMins.Float64,
There's a small possibility this breaks something. I might not have included it, but at one point i was doing weird float to int typcasting which is why it didnt have the float64 type. We can merge this and see if it breaks. I suspect it is ok

2024-12-15 13:00 UTC, Tris20 approved these changes

2024-12-15 13:04 UTC, merged